/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller
import Hanoi._

object App {
  def main(args: Array[String]): Unit = {
  }

  def greeting(): String = "Hello, world!"
}
