/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller

object App {
  def main(args: Array[String]): Unit = {
    println(t())
  }

  def greeting(): String = "Hello, world!"
  
  def t(): String = {
    val h = new Hanoi()
    h.TorresHanoi(6, 1, 2, 3).toString()
  }
}
